### ISSUE TITLE
Unstable Release 9.1.2

### ISSUE THREAD

**Issue by herculesjr** [MortenGregersen/Bagbutik#169]
As part of #168 it introduced an "unstable" release for the Zip dependency so if you try to use SPM with that version it will fail with an error similar to this:

<img width="1053" alt="Screenshot 2024-02-15 at 4 25 19 PM" src="https://github.com/MortenGregersen/Bagbutik/assets/1659664/91111487-ed27-4297-aba7-2893c264443d">

I'm not sure what's the best course of action here but it might be a good idea to look into removing the Zip dependency.
A hacky/faster solution would be to spin up a process calling the `unzip` command using https://developer.apple.com/documentation/foundation/process# since it's only being used for that purpose for the CLI.

I can work on it if this is an acceptable change.

**Comment by MortenGregersen** [comment]
I think it is a fine solution to remove the Zip dependency and use the built-in `unzip` command. I expect it to be available on Linux as well.

Thank you for looking into this. You are very welcome to make a pull request with the change.

**Comment by herculesjr** [comment]
Thank you for your quick response to this :)
