### ISSUE TITLE
CiScheduledStartCondition.Schedule.days has type Items? instead of [Items]?

### ISSUE THREAD

**Issue by alexandrereol** [MortenGregersen/Bagbutik#189]
Hi Morten,

There's a small issue in the `CiScheduledStartCondition.Schedule` model for Xcode Cloud. Currently the type of `days` for a scheduled start is the day itself instead of an array of days as specified in the App Store Connect API.

https://github.com/MortenGregersen/Bagbutik/blob/25f424b2e8fe3131d11cc2d7c2fca43c00a7b75f/Sources/Bagbutik-Models/XcodeCloud/CiScheduledStartCondition.swift#L45

where as App Store Connect API would expect something like:
```swift
public var days: [String]?
public var days: [Items]? // In Bagbutik's case
```

Check the API specs for more info: [CiScheduledStartCondition.Schedule](https://developer.apple.com/documentation/appstoreconnectapi/cischeduledstartcondition/schedule)

**Comment by MortenGregersen** [comment]
Good catch, @alexandrereol! 👍🏻 

I actually had a test around exactly this property, but it was also wrong 😅 
I have fixed the decoding and regenerated the code - there was also another schema with a array property of enum values.

The PR will be merged, when it is green, and I will cut a new release! 🚀

**Comment by MortenGregersen** [comment]
It is done! 🎉 https://github.com/MortenGregersen/Bagbutik/releases/tag/12.0.1
